import javax.swing.Timer;

public class Sunflower extends gamePlay {
    private boolean collect;
    private static final int money = 25;

    public Sunflower() {
    	
        this.collect = false;
    }
    
    //Generates a sun after the counter is 0
    public void generateSun() {
        if (getCounter() == 0) {
            System.out.println("Collect the Sun");
            this.setCounter(3);
            this.collect = true;
        }
    }
    
    //returns the money generated by the sunflower
    public int collectSun(){
        this.collect = false;
        return money;
    }
    
    public boolean isCollect() {
        return collect;
    }
}
